export const SIGNIN_MODAL= `SIGNIN`
export const SIGNUP_MODAL= `SIGNUP`
export const FORGET_PASSWORD_MODAL= `FORGET_PASSWORD`
export const FORGET_PASSWORD_SUBMIT_MODAL= `FORGET_PASSWORD_SUBMIT`
export const OTP_MODAL= `OTP`